# Generated by Django 4.1.3 on 2022-12-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='finished',
            new_name='completed',
        ),
    ]
